### ISSUE TITLE
-conf creating problems

### ISSUE THREAD

**Issue by codeAC29** [e-lab/train-net-master-multiGPU#2]
I was not able to train my network but disabling -conf worked.
Both, the stack trace and the architecture can be seen in the attached image.

<img width="1649" alt="screen shot 2015-11-23 at 11 47 19 am" src="https://cloud.githubusercontent.com/assets/12651576/11343619/d12f084e-91da-11e5-81fc-51fb63c3264b.png">

**Comment by Atcold** [comment]
Thank you @codeAC29, this is the same error I was facing after 18 epochs... I'm not sure why you're getting this. I'm working on it.

**Comment by codeAC29** [comment]
th main.lua -data YYY -cache ZZZ -netType td-road-net -backend cud

**Comment by Atcold** [comment]
@codeAC29, this is not a bug.
You have 3 classes
```lua
{
  1 : "bg"
  2 : "vehicle"
  3 : "road"
}
```
but your network outputs a `17`-dim CPD.

So, how many classes do you have, `3` or `17`?

**Comment by Atcold** [comment]
@culurciello, the bug was not the same... :disappointed:
